Website_recruiting_students_to_participate_in_activities/Website_recruiting_students_to_participate_in_activities/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from Website_recruiting_students_to_participate_in_activities import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('recruitment_announcer/', include('recruitment_announcer.urls')),
    path('', include('register_login.urls')),
    # path('',include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Website_recruiting_students_to_participate_in_activities/recruitment_announcer/urls.py
from django.urls import path
from recruitment_announcer.views import *

urlpatterns = [
    path('',home, name='home1'),
    path('create_activity/', create_activity, name='create_activity'),
    path('delete/<int:id>/', delete, name='delete'),
    path('activity/<int:id>/', activityre),
    path('update_activity/<int:id>/', update_activity, name="update_activity"),
]

Website_recruiting_students_to_participate_in_activities/students/urls.py
from django.urls import path
from students.views import *

from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('',login_required(home,login_url="/login"), name='home'),
    path('activity/<int:id>/', activity)
]

Website_recruiting_students_to_participate_in_activities/recruitment_announcer/models.py
from django.db import models

# Create your models here.
class db_create_activity(models.Model):
    img_activity = models.ImageField(upload_to='media/activity/', blank=True, null=True)
    activity_name = models.CharField(max_length=30)
    activity_type = models.CharField(max_length=30)
    start_date_create_activity = models.DateField()
    due_date_create_activity = models.DateField()
    target_number = models.IntegerField()
    place = models.CharField(max_length=30)
    start_date_activity = models.DateField()
    due_date_activity = models.DateField()
    person_responsible_project = models.CharField(max_length=30)
    project_consultant = models.CharField(max_length=30)
    description = models.CharField(max_length=30)

    def __str__(self) -> str:
        return f'{self.id} {self.img_activity} {self.activity_name} {self.activity_type} {self.start_date_create_activity} {self.due_date_create_activity} {self.target_number} {self.place} {self.start_date_activity} {self.due_date_activity} {self.start_date_activity} {self.person_responsible_project} {self.project_consultant} {self.description}'

Website_recruiting_students_to_participate_in_activities/recruitment_announcer/forms.py
from django import forms
from recruitment_announcer.models import db_create_activity

class forms_create_activity(forms.ModelForm):
    class Meta:
        model = db_create_activity
        fields = '__all__'

        labels = {
            'img_activity' : 'รูปกิจกรรม ',
            'activity_name' : 'ชื่อกิจกรรม ',
            'activity_type' : 'ด้านที่ ',
            'start_date_create_activity' : 'วันที่เปิดรับสมัคร ',
            'due_date_create_activity' : 'วันที่ปิดรับสมัคร ',
            'target_number' : 'จำนวนเป้าหมาย ',
            'place' : 'สถานที่จัดกิจกรรม ',
            'start_date_activity' : 'วันที่จัดกิจกรรม ',
            'due_date_activity' : 'วันที่สิ้นสุดกิจกรรม ',
            'person_responsible_project' : 'ผู้รับผิดชอบโครงการ ',
            'project_consultant' : 'ที่ปรึกษาโครงการ ',
            'description' : 'คำอธิบาย ',
        }

Website_recruiting_students_to_participate_in_activities/recruitment_announcer/views.py
from django.shortcuts import render, redirect

# Create your views here.

from django.shortcuts import render

from recruitment_announcer.models import db_create_activity

# Create your views here.
from recruitment_announcer.forms import forms_create_activity
# Create your views here.

def create_activity(req):
    form = forms_create_activity()
    if req.method == 'POST':
        form = forms_create_activity(req.POST, req.FILES)
        if form.is_valid():
            form.save()
            return redirect('/recruitment_announcer')
    return render(req, 'recruitment_announcer/create_activity.html',{
        'form':form,
        'db': db_create_activity.objects.all()
        })

def update_activity(req, id):
    db = db_create_activity.objects.get(pk=id)
    form = forms_create_activity(instance=db)
    if req.method == 'POST':
        form = forms_create_activity(req.POST, req.FILES, instance=db)
        if form.is_valid():
            form.save()
            return redirect('/recruitment_announcer')
    return render(req, 'recruitment_announcer/update_activity.html',{
        'form':form,
        'i': db
        })

def home(req):
    c = db_create_activity.objects.all()
    return render(req, 
           'recruitment_announcer/home.html',
           {'db': c,})

def delete(req, id):
    db_create_activity.objects.get(pk=id).delete()
    return redirect('/recruitment_announcer')
    
def activityre(req, id):
    a = db_create_activity.objects.get(pk=id)
    return render(req, 'recruitment_announcer/activity.html', {'i':a})

Website_recruiting_students_to_participate_in_activities/recruitment_announcer/templates/recruitment_announcer/components/create_activitys.html
{% load crispy_forms_tags %}

<div class="px-5 font-bold pt-3 w-full h-aoto left-aoto absolute top-aoto border border-gray-600 bg-gray-400 shadow-md">
    สร้างประกาศรับสมัครนักศึกษาเข้าร่วมกิจกรรม <br>
    <div class="px-5">
        : กรอกข้อมูลการประกาศรับสมัคร
    </div>
    <br>
</div>
<div class="w-full h-full pt-0">
      <div class="static w-full h-20 flex flex-col mx-auto p-3 border border-gray-600  shadow-md">
                      {{ course.title_th }}
                 </div>                
              </div>
            </div>
          </div>
      </div>
    </a>
  </div>
  <div class="w-full pt-0">
      <div class="static w-full h-aoto flex flex-col mx-auto p-3 border border-gray-600 shadow-md">
        <form action="{% url 'create_activity' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- {{ form|crispy }} -->
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_activity_name" class="px-6">ชื่อกิจกรรม :</label>
        <input type="text" name="activity_name"  id="id_activity_name"
            class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_activity_type">ด้านที่ :</label>
        <input type="text" name="activity_type" id="id_activity_type"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_start_date_create_activity">วันที่เปิดรับสมัคร :</label>
        <input type="date" name="start_date_create_activity" id="id_start_date_create_activity"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_due_date_create_activity">วันที่ปิดรับสมัคร :</label>
        <input type="date" name="due_date_create_activity" id="id_due_date_create_activity"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_target_number">จำนวนเป้าหมาย :</label>
        <input type="text" name="target_number" id="id_target_number"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_place">สถานที่จัดกิจกรรม :</label>
        <input type="text" name="place" id="id_place"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_start_date_activity">วันที่จัดกิจกรรม :</label>
        <input type="date" name="start_date_activity" id="id_start_date_activity"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_due_date_activity">วันที่สิ้นสุดกิจกรรม :</label>
        <input type="date" name="due_date_activity" id="id_due_date_activity"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_person_responsible_project">ผู้รับผิดชอบโครงการ :</label>
        <input type="text" name="person_responsible_project" id="id_person_responsible_project"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_project_consultant">ที่ปรึกษาโครงการ :</label>
        <input type="text" name="project_consultant" id="id_project_consultant"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_description">คำอธิบาย :</label>
        <input type="text" name="description" id="id_description"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="flex justify-around my-3 drop-shadow-xl rounded-xl bg-blue-100
            px-10 py-2">
        <label for="id_img_activity">รูปกิจกรรม :</label>
        <input type="file" name="img_activity" accept="image/*" id="id_img_activity"
        class="rounded-md drop-shadow-md px-6">
    </div>
    <div class="text-center">
        <br>
    <button type="submit" class="bg-cyan-100 px-6 py-2 round-md drop-shadow-md">
        สร้างกิจกรรม
    </button>
</div>
        </form>
                 </div>
            <!-- {% for i in db %}
                {{i.id}}<br>
                {% if i.img_activity %}
                    <img src="{{i.img_activity.url}}" alt="media/activity/images" />
                {% endif %}
                    <a href="{% url 'delete' i.id %}" class="px-2">
                    <svg class="w-8 h-8 text-red-400" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M20.25 7.5l-.625 10.632a2.25 2.25 0 01-2.247 2.118H6.622a2.25 2.25 0 01-2.247-2.118L3.75 7.5m6 4.125l2.25 2.25m0 0l2.25 2.25M12 13.875l2.25-2.25M12 13.875l-2.25 2.25M3.375 7.5h17.25c.621 0 1.125-.504 1.125-1.125v-1.5c0-.621-.504-1.125-1.125-1.125H3.375c-.621 0-1.125.504-1.125 1.125v1.5c0 .621.504 1.125 1.125 1.125z"></path>
                    </svg>
                </a>
            {% endfor %} -->
              </div>
            </div>
          </div>
      </div>
    </a>
  </div>

Website_recruiting_students_to_participate_in_activities/recruitment_announcer/templates/recruitment_announcer/components/data.html
<div class="w-full pt-0">
  <div class="static w-full h-20 flex flex-col mx-auto p-3  shadow-md">
    </div>
{% for i in db %}
<div class="w-full pt-0">
  <div class="container mx-auto p-4">
      <table class="w-full table-auto">
          <thead>
              <tr>            
                <th class="border px-4 py-2">{{i.start_date_create_activity}}</th>
                {% if i.img_activity %}
                <th class="border px-4 py-3 invisible md:visible flex justify-around"><img src="{{i.img_activity.url}}" alt="media/activity/images" width="70" height="70"></th>
                {% endif %}
                <th class="border text-xl"><a href="activity/{{ i.id }}">{{i.activity_name}}</a><br>
                <div class="text-sm">
                  : รับจำนวน {{i.target_number}} คน
                </div>
                </th>
                  <th class="border text-xl">ด้านที่ {{i.activity_type}}<br>
                  <div class="text-sm">
                  จำนวนรับ / เหลือ<br>
                  10 / 10
                  </div>
                  </th>
                <th class="border">คณะวิทยาศาสตร์</th>
                <th class="border">กำลังรับสมัคร</th>
                <th class="border px-4"><a href="update_activity/{{ i.id }}/">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#319eb9" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-file-pen-line">
                    <path d="m18 5-3-3H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2"/>
                    <path d="M8 18h1"/>
                    <path d="M18.4 9.6a2 2 0 1 1 3 3L17 17l-4 1 1-4Z"/>
                  </svg>
                </a>
                </th>
                <th class="border px-4"><a href="delete/{{ i.id }}/">
                  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#ff0000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trash-2">
                    <path d="M3 6h18"/>
                    <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/>
                    <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/>
                    <line x1="10" x2="10" y1="11" y2="17"/>
                    <line x1="14" x2="14" y1="11" y2="17"/>
                  </svg>
                  </a>
              </th>
              </tr>
          </thead>
      </table>
  </div>
</div>
{% endfor %}

Website_recruiting_students_to_participate_in_activities/recruitment_announcer/templates/recruitment_announcer/components/data_activity.html
<div class="w-full pt-0">
    <div class="static w-full h-20 flex flex-col mx-auto p-3  shadow-md">
      </div>
  <body class="w-full pt-0">
    <div class="container mx-auto p-4">
        <table class="w-full table-auto">
            <thead>
                {% if i.img_activity %}
                <th class="border px-2 py-3 invisible md:visible flex justify-around"><img src="{{i.img_activity.url}}" alt="media/activity/images" width="170" height="170"></th>
                {% endif %}
                <td class="border px-4 py-3">ชื่อกิจกรรม : {{i.activity_name}}<br>
                <br>
                ด้านที่ : {{i.activity_type}}<br>
                <br>
                วันที่เปิดรับสมัคร : {{i.start_date_create_activity}} - {{i.due_date_create_activity}}<br>
                <br>
                จำนวนเป้าหมาย : {{i.target_number}}<br>
                </td>
            </thead>
        </table>
        <table class="w-full table-auto">
            <thead>
                <td class="border px-4 py-3">
                    สถานที่จัดกิจกรรม : {{i.place}}<br>
                    <br>
                    วันที่จัดกิจกรรม : {{i.start_date_activity}} - {{i.due_date_activity}}<br>
                    <br>
                    ผู้รับผิดชอบโครงการ : {{i.person_responsible_project}}<br>
                    <br>
                    ที่ปรึกษาโครงการ : {{i.project_consultant}}<br>
                    <br>
                    คำอธิบาย : {{i.description}}<br>
                    <br>
                </td>
            </thead>
        </table>
    </div>
  </body>
  </html>

Website_recruiting_students_to_participate_in_activities/recruitment_announcer/templates/recruitment_announcer/components/update_activitys.html
<div class="w-full pt-0">
    <div class="static w-full h-20 flex flex-col mx-auto p-3  shadow-md">
      </div>
  <body class="w-full pt-0">
    <div class="container mx-auto p-4">
        <form action="" method="post" enctype="multipart/form-data">
            <table class="w-full table-auto">
                {% csrf_token %}
                <thead>
                    {% if i.img_activity %}
                    <th class="border px-2 py-3 invisible md:visible flex justify-around">
                        <img src="{{i.img_activity.url}}" alt="media/activity/images" width="170" height="170">
                    </th>
                    {% endif %}
                    <input type="file" name="img_activity" accept="image/*" id="id_img_activity">
                    <td class="border px-4 py-3">ชื่อกิจกรรม : {{form.activity_name}}<br>
                    <br>
                    ด้านที่ : {{form.activity_type}}<br>
                    <br>
                    วันที่เปิดรับสมัคร : {{form.start_date_create_activity}} - {{form.due_date_create_activity}}<br>
                    <br>
                    จำนวนเป้าหมาย : {{form.target_number}}<br>
                    </td>
                </thead>
            </table>
            <table class="w-full table-auto">
                <thead>
                    <td class="border px-4 py-3">
                        สถานที่จัดกิจกรรม : {{form.place}}<br>
                        <br>
                        วันที่จัดกิจกรรม : {{form.start_date_activity}} - {{form.due_date_activity}}<br>
                        <br>
                        ผู้รับผิดชอบโครงการ : {{form.person_responsible_project}}<br>
                        <br>
                        ที่ปรึกษาโครงการ : {{form.project_consultant}}<br>
                        <br>
                        คำอธิบาย : {{form.description}}<br>
                        <br>
                        <button type="submit" class="bg-cyan-100 px-6 py-2 round-md drop-shadow-md">
                            บันทึกการแก้ไข
                        </button>
                    </td>
                </thead>
            </table>
        </form>
    </div>
  </body>
  </html>